# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: natures_plate_development
  pool: 5
  username: natures_plate
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: natures_plate_test
  pool: 5
  username: natures_plate 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: natures_plate_production
  pool: 5
  username: natures_plate 
  password:


